### ISSUE TITLE
Is it possible to make a .cbz after download?

### ISSUE THREAD

**Issue by Zhen-Bo** [gisellevonbingen/DoujinshiDownloader#14]
Now I can only make it to .zip file and manually change the ext filename to .cbz
Is it great to auto archive to .cbz file

**Comment by gisellevonbingen** [comment]
Is it ok to just change extension only?

**Comment by gisellevonbingen** [comment]
Instead of the function 'changing the extension of the downloaded file',
I will add a function to run an executable file for each specific event.
And it will provide a list of variables, which will help to process the file automatically.

Event Example: `download start`, `download success`.
Variable Example: download directory, `zip file path`, `zip file name`, `gallery title`. etc.

Then, to implement the function you want, you can set it as below in the GUI.
For change extension to .cbz automatically on download success.
1. Select hook name was `'Download Success'` in Hook panel in Config form.
2. Enter `'rename "${DowloadPath}" "${DownloadFileNameWithoutExt}.cbz"'` at command line.
3. Save config.
4. Download a gallery you want.

**Comment by Zhen-Bo** [comment]
> Is it ok to just change extension only?

Yes Only need to change .zip to .cbz

**Comment by gisellevonbingen** [comment]
Ok, new version released include can do what do you want.
Can you test it?
Changelog and file : https://github.com/gisellevonbingen/DoujinshiDownloader/releases/tag/01.02.00.00
Commandline Guide : https://github.com/gisellevonbingen/DoujinshiDownloader/wiki/Event-Hook#1-change-extension-to-cbz-after-download-complete
